In [86]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [87]:
xy = np.loadtxt('home_out.csv', delimiter=",", dtype=np.int32)

In [88]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

X = xy[0:,0:-1]
print(X)
Y = xy[0:,5:6]
y = Y.ravel()
print(y)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)



[[144  42   7   1   1]
 [121  41  10   1   1]
 [129  39   9   1   0]
 ...
 [117  37  10   1   2]
 [138  42   8   1   0]
 [103  43  14   1   0]]
[48 44 41 ... 42 47 46]


In [89]:
clf = RandomForestClassifier(n_estimators=100,max_depth=2,random_state=0)

In [90]:
forest = clf.fit(X_train,y_train)
RandomForestClassifier(bootstrap=True,class_weight=None,criterion='gini',max_depth=2, 
                       max_features=4, max_leaf_nodes=None,min_impurity_decrease=0.0,
                       min_impurity_split=None,min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
                       oob_score=False, random_state=0, verbose=0, warm_start=False)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=2, max_features=4, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [91]:
print(clf.feature_importances_)
predict = clf.predict(X_test)
print(predict)
print(list(y_test))

[0.00877584 0.54695354 0.03081167 0.32619752 0.08726143]
[45 44 48 ... 43 48 47]
[46, 45, 47, 44, 42, 47, 50, 41, 46, 44, 48, 44, 40, 46, 47, 45, 45, 43, 41, 43, 47, 47, 47, 48, 44, 45, 39, 46, 46, 46, 46, 49, 40, 47, 46, 45, 45, 43, 45, 46, 45, 49, 45, 46, 41, 49, 45, 44, 41, 45, 44, 45, 44, 45, 45, 47, 51, 48, 47, 45, 41, 43, 43, 45, 48, 45, 49, 44, 45, 44, 44, 40, 47, 41, 43, 43, 44, 46, 45, 42, 44, 43, 46, 44, 40, 45, 49, 47, 42, 47, 45, 48, 41, 45, 43, 49, 45, 47, 43, 43, 44, 46, 41, 49, 50, 44, 44, 50, 41, 46, 45, 43, 42, 40, 43, 47, 46, 42, 46, 50, 48, 46, 48, 48, 46, 43, 46, 49, 48, 46, 49, 46, 42, 43, 42, 42, 46, 47, 45, 47, 44, 46, 42, 38, 47, 48, 45, 43, 44, 45, 45, 44, 48, 43, 44, 45, 40, 42, 44, 44, 45, 48, 44, 48, 46, 46, 44, 45, 46, 42, 48, 45, 39, 51, 47, 45, 47, 44, 46, 40, 42, 44, 44, 45, 49, 45, 44, 44, 45, 46, 42, 46, 47, 42, 44, 43, 49, 46, 46, 41, 45, 49, 43, 45, 49, 42, 43, 47, 48, 44, 39, 46, 43, 44, 49, 47, 40, 44, 47, 42, 48, 44, 41, 44, 46, 41, 47, 47, 41, 43

In [92]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

In [93]:
 print('정확도 :', metrics.accuracy_score(y_test, predict))

정확도 : 0.2255


In [156]:
number = 0
score3 = 0


while number < 1999:
    if predict[number] >= y_test[number] - 3 and predict[number] <= y_test[number] + 3:
        score3 = score3 + 1
    number = number + 1

In [157]:
number = 0
score2 = 0


while number < 1999:
    if predict[number] >= y_test[number] - 2 and predict[number] <= y_test[number] + 2:
        score2 = score2 + 1
    number = number + 1

In [158]:
number = 0
score1 = 0


while number < 1999:
    if predict[number] >= y_test[number] - 1 and predict[number] <= y_test[number] + 1:
        score1 = score1 + 1
    number = number + 1

In [159]:
print(score3/2000)
print(score2/2000)
print(score1/2000)

0.954
0.857
0.619
